### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by robertbaker** [kirjs/gulp-fixmyjs#5]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error when running fixmyjs:

---
'use strict';

var gulp = require('gulp');
var browserSync = require('browser-sync');
var fixmyjs = require("gulp-fixmyjs");
var $ = require('gulp-load-plugins')();

module.exports = function(options) {
  gulp.task('scripts', function () {
    return gulp.src(options.src + '/{app,components}/**/*.js')
      .pipe(fixmyjs({
        // JSHint settings here
      }))
      .pipe($.jshint())
      .pipe($.jshint.reporter('jshint-stylish'))
      .pipe(browserSync.reload({ stream: true }))
      .pipe($.size());
  });
};

**Comment by kirjs** [comment]
Hi Rob, 

I could not reproduce it on my machine, so maybe it depends on the content. 

I made gulp-fixmyjs print the stacktrace in case of an error, can you please run it with 1.0.1 and let me know which exact error it prints out?

**Comment by robertbaker** [comment]
Error: Error when running fixmyjs:
TypeError: Cannot read property 'camelcase' of undefined
    at validateRules (d:\CodeRoot\node_modules\gulp-fixmyjs\node_modules\fixmyjs\lib\index.js:44:14)
    at Function.fixMyJS.fix (d:\CodeRoot\node_modules\gulp-fixmyjs\node_modules\fixmyjs\lib\index.js:76:5)
    at fixJS (d:\CodeRoot\node_modules\gulp-fixmyjs\index.js:23:20)
    at DestroyableTransform.<anonymous> (d:\CodeRoot\node_modules\gulp-fixmyjs\index.js:59:38)
    at respond (d:\CodeRoot\node_modules\gulp-fixmyjs\node_modules\rcloader\index.js:56:32)
    at respond (d:\CodeRoot\node_modules\gulp-fixmyjs\node_modules\rcloader\node_modules\rcfinder\index.js:140:7)
    at d:\CodeRoot\node_modules\gulp-fixmyjs\node_modules\rcloader\node_modules\rcfinder\index.js:124:17
    at d:\CodeRoot\node_modules\gulp-fixmyjs\node_modules\rcloader\node_modules\rcfinder\index.js:77:13
    at process._tickCallback (node.js:355:11)

**Comment by robertbaker** [comment]
I'm using yo gulp-angular if that makes a difference.

**Comment by kirjs** [comment]
I was able ho reproduce the issue, and  the reason was `// comments` in `.jshintrc` file, which rcloader library used for parsing doesn't know how to handle. 

Temporary workaround would be to just remove the comments, from  `.jshintrc` file. 

I created an issue for rcloader, hopefully that can be fixed. 
https://github.com/spalger/rcloader/issues/6

**Comment by robertbaker** [comment]
Thanks!
