### ISSUE TITLE
Allow comments in .jshintrc file

### ISSUE THREAD

**Issue by saranshkataria** [kirjs/gulp-fixmyjs#7]
If there are comments in jshintrc file, I get an exception
Error: Error when reading .jshint config:
SyntaxError: Unexpected token /

**Comment by kirjs** [comment]
Seems like this issue belongs to [fixmyjs repository](https://github.com/jshint/fixmyjs)
Let me see if there is a new version though.

**Comment by kirjs** [comment]
Feel free to reopen
